// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv48ejnyGAh_95jURMtsB1g9_IqKNp0pE',
    appId: '1:179876622729:web:f4c46a86f901eeeaf4b158',
    messagingSenderId: '179876622729',
    projectId: 'email-password-auth-42407',
    authDomain: 'email-password-auth-42407.firebaseapp.com',
    storageBucket: 'email-password-auth-42407.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaF-aq-FuZ9J4ZhEckIIBZcPZS1uDQsqY',
    appId: '1:179876622729:android:baed9190f557d847f4b158',
    messagingSenderId: '179876622729',
    projectId: 'email-password-auth-42407',
    storageBucket: 'email-password-auth-42407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8fAGsVbmOlQHbEoq_lOd5TvhmIejwWA',
    appId: '1:179876622729:ios:5df70a73d46b0974f4b158',
    messagingSenderId: '179876622729',
    projectId: 'email-password-auth-42407',
    storageBucket: 'email-password-auth-42407.appspot.com',
    iosClientId: '179876622729-5s9mbos29coke2t4u19rm6ircik0594t.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw8fAGsVbmOlQHbEoq_lOd5TvhmIejwWA',
    appId: '1:179876622729:ios:5df70a73d46b0974f4b158',
    messagingSenderId: '179876622729',
    projectId: 'email-password-auth-42407',
    storageBucket: 'email-password-auth-42407.appspot.com',
    iosClientId: '179876622729-5s9mbos29coke2t4u19rm6ircik0594t.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
